<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ax213="http://com.test/applyForInsurance" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:tns="http://com.test/insurance" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" targetNamespace="http://com.test/insurance">
    <wsdl:types>
        <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="qualified" elementFormDefault="qualified" targetNamespace="http://com.test/applyForInsurance">
            <xs:complexType name="Car">
                <xs:sequence>
                    <xs:element minOccurs="0" name="color" nillable="true" type="xs:string" />
                    <xs:element minOccurs="0" name="style" nillable="true" type="xs:string" />
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="Driver">
                <xs:sequence>
                    <xs:element minOccurs="0" name="age" type="xs:int" />
                    <xs:element minOccurs="0" name="male" type="xs:boolean" />
                    <xs:element minOccurs="0" name="name" nillable="true" type="xs:string" />
                </xs:sequence>
            </xs:complexType>
            <xs:element name="applyForInsurance">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element maxOccurs="unbounded" minOccurs="0" name="carInsurance" type="ax213:Car" />
                        <xs:element maxOccurs="unbounded" minOccurs="0" name="driverInsurance" type="ax213:Driver" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:complexType name="Policy">
                <xs:sequence>
                    <xs:element minOccurs="0" name="premium" type="xs:double" />
                </xs:sequence>
            </xs:complexType>
            <xs:element name="insurancerApplicationRespone">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element maxOccurs="unbounded" minOccurs="0" name="insurancePolicy" type="ax213:Policy" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:schema>
    </wsdl:types>
    <wsdl:message name="applyForInsuranceRequestMessage">
        <wsdl:part name="parameters" element="ax213:applyForInsurance" />
    </wsdl:message>
    <wsdl:message name="applyForInsuranceResponseMessage">
        <wsdl:part name="parameters" element="ax213:insurancerApplicationRespone" />
    </wsdl:message>
    <wsdl:portType name="InsuranceServicePortType">
        <wsdl:operation name="applyForInsurance">
            <wsdl:input message="tns:applyForInsuranceRequestMessage" wsaw:Action="urn:applyForInsurance" />
            <wsdl:output message="tns:applyForInsuranceResponseMessage" wsaw:Action="urn:applyForInsuranceResponse" />
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="InsuranceServiceSoap11Binding" type="tns:InsuranceServicePortType">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document" />
        <wsdl:operation name="applyForInsurance">
            <soap:operation soapAction="urn:applyForInsurance" style="document" />
            <wsdl:input>
                <soap:body use="literal" />
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" />
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:binding name="InsuranceServiceSoap12Binding" type="tns:InsuranceServicePortType">
        <soap12:binding transport="http://schemas.xmlsoap.org/soap/http" style="document" />
        <wsdl:operation name="applyForInsurance">
            <soap12:operation soapAction="urn:applyForInsurance" style="document" />
            <wsdl:input>
                <soap12:body use="literal" />
            </wsdl:input>
            <wsdl:output>
                <soap12:body use="literal" />
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:binding name="InsuranceServiceHttpBinding" type="tns:InsuranceServicePortType">
        <http:binding verb="POST" />
        <wsdl:operation name="applyForInsurance">
            <http:operation location="applyForInsurance" />
            <wsdl:input>
                <mime:content type="text/xml" part="parameters" />
            </wsdl:input>
            <wsdl:output>
                <mime:content type="text/xml" part="parameters" />
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="InsuranceService">
        <wsdl:port name="InsuranceServiceHttpsSoap11Endpoint" binding="tns:InsuranceServiceSoap11Binding">
            <soap:address location="https://10.100.3.69:9443/services/InsuranceService.InsuranceServiceHttpsSoap11Endpoint/" />
        </wsdl:port>
        <wsdl:port name="InsuranceServiceHttpSoap11Endpoint" binding="tns:InsuranceServiceSoap11Binding">
            <soap:address location="http://10.100.3.69:9763/services/InsuranceService.InsuranceServiceHttpSoap11Endpoint/" />
        </wsdl:port>
        <wsdl:port name="InsuranceServiceHttpsSoap12Endpoint" binding="tns:InsuranceServiceSoap12Binding">
            <soap12:address location="https://10.100.3.69:9443/services/InsuranceService.InsuranceServiceHttpsSoap12Endpoint/" />
        </wsdl:port>
        <wsdl:port name="InsuranceServiceHttpSoap12Endpoint" binding="tns:InsuranceServiceSoap12Binding">
            <soap12:address location="http://10.100.3.69:9763/services/InsuranceService.InsuranceServiceHttpSoap12Endpoint/" />
        </wsdl:port>
        <wsdl:port name="InsuranceServiceHttpsEndpoint" binding="tns:InsuranceServiceHttpBinding">
            <http:address location="https://10.100.3.69:9443/services/InsuranceService.InsuranceServiceHttpsEndpoint/" />
        </wsdl:port>
        <wsdl:port name="InsuranceServiceHttpEndpoint" binding="tns:InsuranceServiceHttpBinding">
            <http:address location="http://10.100.3.69:9763/services/InsuranceService.InsuranceServiceHttpEndpoint/" />
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>